version: 2.1
references:
  pre_checkout: &pre_checkout
    run:
        name: Pre Checkout
        command: |
          stat -c '%y' /opt/ros/$ROS_DISTRO/setup.sh | \
            sha256sum | \
            awk '{print "distro "$1}' > /opt/ros/$ROS_DISTRO/checksum.txt
            find $BBR_WS/src -not -iwholename '*.git/*' -name 'package.xml' -type f -exec sha256sum {} \; | \
              sort -k 2 | \
              cut -d" " -f1 | \
              sha256sum | \
              awk '{print "package "$1}' > /tmp/package.txt
          rm -rf $BBR_WS/*
  post_checkout: &post_checkout
    run:
        name: Post Checkout
        command: |
          find $BBR_WS/src -not -iwholename '*.git/*' -name 'package.xml' -type f -exec sha256sum {} \; | \
            sort -k 2 | \
            cut -d" " -f1 | \
            sha256sum | \
            awk '{print "package "$1}' > $BBR_WS/package.txt
  install_dependencies: &install_dependencies
    run:
        name: Install Dependencies
        command: |
          cat /opt/ros/$ROS_DISTRO/checksum.txt > $BBR_WS/checksum.txt
          find $BBR_WS/src -not -iwholename '*.git/*' -type f -exec sha256sum {} \; | \
            sort -k 2 | \
            cut -d" " -f1 | \
            sha256sum | \
            awk '{print "source "$1}' >> $BBR_WS/checksum.txt
          if ! cmp /tmp/package.txt $BBR_WS/package.txt 2>&1
          then
            echo "Install Dependencies"
            apt-get update
            dependencies=$(
              rosdep install -q -y \
                --from-paths \
                  src \
                --ignore-src \
                --verbose | \
              awk '$1 ~ /^resolution\:/' | \
              awk -F'[][]' '{print $2}' | \
              tr -d \, | xargs -n1 | sort -u | xargs)
            dpkg -s $dependencies | \
              sha256sum | \
              awk '{print "dependencies "$1}' >> $BBR_WS/checksum.txt
          fi
  store_build_checksum: &store_build_checksum
    store_artifacts:
        path: checksum.txt
  restore_build_cache: &restore_build_cache
    restore_cache:
      name: Restore Build Cache
      key: build-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "/opt/bbr_ws/checksum.txt" }}
  source_build: &source_build
    run:
      name: Source Build
      command: |
        if [ -d install ]
        then
            echo "Skipping Source Build"
        else
            . $ROS_WS/install/setup.sh
            colcon build \
              --symlink-install \
              --cmake-args \
                --no-warn-unused-cli \
                -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE \
                -DCOVERAGE_ENABLED=$COVERAGE_ENABLED \
                -DCMAKE_CXX_FLAGS="-Wno-unused-parameter"
        fi
  save_build_cache: &save_build_cache
    save_cache:
      name: Save Build Cache
      key: build-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "/opt/bbr_ws/checksum.txt" }}
      paths:
        - /opt/bbr_ws
  copy_build_logs: &copy_build_logs
    run:
        name: Copy Build Logs
        when: always
        command: cp -rH log/latest_build log/build
  store_build_logs: &store_build_logs
    store_artifacts:
        path: log/build
  test_build: &test_build
    run:
        name: Test Build
        command: |
          colcon test
  copy_test_logs: &copy_test_logs
    run:
        name: Copy Test Logs
        when: always
        command: cp -rH log/latest_test log/test
  store_test_logs: &store_test_logs
    store_artifacts:
        path: log/test
  report_code_coverage: &report_code_coverage
    run:
        name: Report Code Coverage
        command: |
          if [ "$COVERAGE_ENABLED" = "True" ]
          then
            . install/setup.sh
            src/bbr_ros2/tools/code_coverage_report.bash codecovio
          else
            echo "Skipping Code Coverage Report"
          fi

commands:
  checkout_source:
    description: "Checkout Source"
    steps:
      - *pre_checkout
      - *post_checkout
      - checkout:
          path: src/bbr_ros2
      - *post_checkout
  build_source:
    description: "Build Source"
    steps:
      - *install_dependencies
      - *store_build_checksum
      - *restore_build_cache
      - *source_build
      - *save_build_cache
      - *copy_build_logs
      - *store_build_logs
  test_source:
    description: "Test Source"
    steps:
      - *test_build
      - *copy_test_logs
      - *store_test_logs
  report_coverage:
    description: "Report Coverage"
    steps:
      - *report_code_coverage

executors:
  docker_exec:
    docker:
      - image: dledr/bbr_ros2:master
    working_directory: /opt/bbr_ws
    environment:
      MAKEFLAGS: "-j 1 -l 1"

jobs:
  debug_build:
    executor: docker_exec
    environment:
      CMAKE_BUILD_TYPE: "Debug"
      COVERAGE_ENABLED: "True"
    steps:
      - checkout_source
      - build_source
      - test_source
      # - report_coverage
  release_build:
    executor: docker_exec
    environment:
      CMAKE_BUILD_TYPE: "Release"
      COVERAGE_ENABLED: "False"
    steps:
      - checkout_source
      - build_source
      - test_source

workflows:
  version: 2
  build-test:
    jobs:
      - debug_build
      - release_build
  # nightly:
  #   triggers:
  #     - schedule:
  #         cron: "0 0 * * *"
  #         filters:
  #           branches:
  #             only:
  #               - master
  #   jobs:
  #     - build
