[package]
name = "bbr_cli"
version = "0.1.0"
authors = ["ruffsl <roxfoxpox@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.2"

[[bin]]
name = "bbr"
path = "src/main.rs"